services:
  web:
    build:
      context: ./apps/web
      dockerfile: ../../docker/web.Dockerfile
    container_name: fixko_web
    volumes:
      - ./apps/web:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
    depends_on:
      - api

  api:
    build:
      context: ./apps/api
      dockerfile: ../../docker/api.Dockerfile
    container_name: fixko_api
    volumes:
      - ./apps/api:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/fixko_db
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: fixko_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fixko_db
    ports:
      - "5437:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: